/// Golden image tests.
///
/// Linux only, on purpose: goldens are generated by the manual
/// `golden-generate` workflow (Linux) and verified by the `golden` job in
/// build.yml (also Linux). Font rasterization differs per OS, so generating on
/// Windows or macOS produces files CI will reject.
///
/// Regenerate deliberately, never to make a red build green:
///   flutter test --update-goldens test_golden/
///
/// Then inspect every image pixel by pixel before committing. A golden that
/// changed for a reason you cannot name is a regression, not an update.
@Tags(['golden'])
library;

import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:image/image.dart' as img;
import 'package:pixelforge/core/controller.dart';
import 'package:pixelforge/ui/widgets/preview.dart';
import 'package:pixelforge/ui/widgets/queue_view.dart';
import 'package:pixelforge/ui/widgets/settings_view.dart';

Uint8List _swatch(int v) {
  final im = img.Image(width: 32, height: 32, numChannels: 3);
  img.fill(im, color: img.ColorRgba8(v, 128, 200, 255));
  return img.encodePng(im);
}

Future<void> _pumpFrame(WidgetTester tester, Widget child, double width) async {
  await tester.pumpWidget(
    MaterialApp(
      home: MediaQuery(
        // Pinned so a goldens result never depends on the machine that
        // produced it.
        data: const MediaQueryData(textScaler: TextScaler.noScaling),
        child: Scaffold(
          body: SizedBox(width: width, height: 700, child: child),
        ),
      ),
    ),
  );
  await tester.pumpAndSettle();
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  group('queue', () {
    testWidgets('empty at 400px', (tester) async {
      final controller = ResizeController();
      addTearDown(controller.dispose);
      await _pumpFrame(tester, QueueView(controller: controller), 400);
      await expectLater(
        find.byType(QueueView),
        matchesGoldenFile('goldens/queue_empty_400.png'),
      );
    });

    testWidgets('with items at 400px', (tester) async {
      final controller = ResizeController();
      addTearDown(controller.dispose);
      controller.addDroppedFiles([
        (name: 'a.jpg', bytes: _swatch(10), path: null),
        (name: 'b.jpg', bytes: _swatch(200), path: null),
      ]);
      await _pumpFrame(tester, QueueView(controller: controller), 400);
      await expectLater(
        find.byType(QueueView),
        matchesGoldenFile('goldens/queue_items_400.png'),
      );
    });
  });

  group('preview', () {
    testWidgets('split at 800px', (tester) async {
      await _pumpFrame(
        tester,
        LargePreview(before: _swatch(10), after: _swatch(200)),
        800,
      );
      await expectLater(
        find.byType(LargePreview),
        matchesGoldenFile('goldens/preview_split_800.png'),
      );
    });
  });

  group('settings', () {
    testWidgets('at 400px', (tester) async {
      final controller = ResizeController();
      addTearDown(controller.dispose);
      await _pumpFrame(tester, SettingsView(controller: controller), 400);
      await expectLater(
        find.byType(SettingsView),
        matchesGoldenFile('goldens/settings_400.png'),
      );
    });

    testWidgets('at 800px', (tester) async {
      final controller = ResizeController();
      addTearDown(controller.dispose);
      await _pumpFrame(tester, SettingsView(controller: controller), 800);
      await expectLater(
        find.byType(SettingsView),
        matchesGoldenFile('goldens/settings_800.png'),
      );
    });
  });
}
